deegree/deegree-ogcapi

pom.xml
sets jersey version to 2.34 for all jersery modules, fixed build error introduced with PR #10
=> Fixes #15 sets same jersey for all jersey modules

deegree-ogcapi-features/src/main/resources/collection.html
Previously, the CRS defined in method registerCrs was hard coded to EPSG:25832.
With this pull request, the value configured in Map element in html/*.xml is registered.
By that, it is possible to change the projection of the map in the collection view (an error occurred when trying to change the CRS before).
Fixes #24.
=> Fix registration of CRS in HTML view

deegree-ogcapi-documentation/src/main/asciidoc/installation.adoc
This PR improves the documentation section "Installation" where to download the deegree OGC API web app and how to use the docker image available at https://hub.docker.com/repository/docker/deegree/deegree-ogcapi.
=> Improved installation section

deegree-ogcapi-features/src/main/resources/collection.html, deegree-ogcapi-features/src/main/resources/feature.html, deegree-ogcapi-features/src/main/resources/features.html
This PR fixes issue #48 by changing the links to recent 6.15.1 version of OL css files.
=> Fixes broken links to OpenLayers CSS files

deegree-ogcapi-features/src/main/resources/collections.html
This PR fixes the HTML collections view for linked metadata
=> Fixes metadata links in collections view (HTML encoding)

deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/OgcApiFeaturesMediaType.java, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/filter/OverrideAcceptFilter.java, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/filter/UnknownParameterFilter.java, deegree-ogcapi-features/src/main/resources/collection.html, deegree-ogcapi-features/src/main/resources/collections.html, deegree-ogcapi-features/src/main/resources/conformance.html, deegree-ogcapi-features/src/main/resources/datasets.html, deegree-ogcapi-features/src/main/resources/feature.html, deegree-ogcapi-features/src/main/resources/features.html, deegree-ogcapi-features/src/main/resources/landingpage.html, deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/filter/OverrideAcceptFilterTest.java
Support overriding accepted format for a request by specifying a query parameter or adding an extension to the request URL:
- if a query parameter "accept" is provided, its value is looked up in the supported list of extension, if not present it is directly used as media type
- otherwise, if the request URL ends on `.` plus a supported extension, the media type associated to the extension is used as media type
- any values provided via the Accept header are appended
See #76. Follows priority for format/encoding as suggested by @stephanr
=> Add support for overriding accepted format

deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/OafResource.java, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/DeegreeDataAccess.java, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/configuration/FeatureTypeMetadata.java, deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/workspace/DeegreeDataAccessTest.java
...instead of the CRS name.
If no match can be found for the storage CRS codes in the list of supported CRS, the first of the storage CRS codes is used.
This is done to if possible fulfill the requirement in the specification of OGC API Features Part 2, that the storage CRS shall be one of the identifiers of the supported CRS.
Since we can't determine for the storage CRS which code was initially used to specify it, we use the list of supported query CRS for deegree OAF as a way to determine the desired code, if possible. So with these changes to fulfill the requirement of the OGC spec you need to specify the desired code for the storage CRS as part of the supported query CRS.
Solves #89
=> Fixes the use of storage CRS code from list of supported CRS

deegree-ogcapi-documentation/src/main/asciidoc/usage.adoc, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/filter/OpenApiAliasFilter.java, deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/resource/OpenApiTest.java
Adds an alias "openapi" for the existing "api" endpoint that serves the OpenAPI definition.
See #76
=> Add "openapi" alias for api endpoint

Dockerfile, README.md, docker/liveness-check.sh
Improvements related to Dockerfile:
- fix health check (now also works if a different context path is configured)
- add example on context path with multiple segments to README
- remove VOLUME instruction from Dockerfile
- make more clear how the workspace root is configured and that the `/workspaces` folder is just a default for the image
=> Dockerfile health check fix and small improvements

deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/link/LinkBuilder.java, deegree-ogcapi-features/src/main/resources/landingpage.html, deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/resource/LandingPageTest.java
This pull request fixes the relation type of the link towards the OpenAPI specification to "service-doc" for text/html media type.
=> Fix link relation type to OpenAPI specification

deegree-ogcapi-features/src/main/resources/collection.html
This pull request adds the itemType to the HTML representation of the collection.
=> Add itemType in collection HTML

deegree-ogcapi-documentation/src/main/asciidoc/configuration.adoc, deegree-ogcapi-documentation/src/main/asciidoc/usage.adoc, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/OgcApiFeaturesMediaType.java, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/resource/OpenApi.java, deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/resource/OpenApiCorsTest.java, deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/resource/OpenApiTest.java
Support serving the OpenAPI description as YAML in addition to the
already supported JSON format.
Also add a configuration option to allow CORS access for all origins. By default this is disabled.
See #76 
**Please note:** Includes changes from PR #81 due to dependency on YAML media type defined there, thus #81 should be merged first.
=> Add OpenAPI description also in YAML format

deegree-ogcapi-config/pom.xml, deegree-ogcapi-features/pom.xml, pom.xml
...because when generating Eclipse projects with Maven, in Eclipse there are compile errors like these if the dependencies are included:
```
The package javax.xml.stream is accessible from more than one module: <unnamed>, java.xml
```
Additional context:
- The Maven build itself does not seem to be impacted by the dependencies, just the Eclipse compiler
- Java version used: 17
- Generated Eclipse projects with command similar to `mvn eclipse:clean eclipse:configure-workspace eclipse:eclipse -Declipse.workspace=<workspace-folder> -Dwtpversion=2.0`
=> Exclude dependencies that are included in Java 11+

deegree-ogcapi-webapp/pom.xml, pom.xml
This PR upgrades the maven plugins surefire, failsafe, javadoc, versions, enforcer, and jetty plugin to latest bugfix version
=> Upgrade maven plugins to latest bugfix version

pom.xml
This PR upgrades JAXB to bugfix version 2.3.9 and deegree to 3.5.4.
=> Upgrade deegree and jaxb to latest bugfix version

pom.xml
This PR upgrades dependencies and maven plugins to latest versions including upgrading to deegree bugfix version 3.5.7 which contains important upgrade of postgresql jdbc driver.
Important:
- This PR shall be merged after https://github.com/deegree/deegree3/pull/1663 into `3.5-main` and bugfix version released. This PR may require an update to the bugfix version containing the required changes.
=> Upgrade dependencies to latests version including deegree 3.5.7

.github/workflows/build_maven.yml, .mvn/wrapper/maven-wrapper.properties, mvnw, mvnw.cmd
This PR adds [Apache Maven wrapper](https://maven.apache.org/wrapper/). The wrapper should work with different operating systems such as:
-   Linux
-  OSX
-  Windows
You can run maven goals like this for the Unix system:
`./mvnw clean install`
=> Add maven wrapper

pom.xml
- Fixed logging
- Upgrade to deegree 3.5.8
=> Fixed logging by downgrading slf4j version, upgrade deegree version

.github/workflows/build_docker.yml, docker/1.3/Dockerfile
PR switches gh action building docker image to release version 1.3.0.
=> Updates gh action building docker image to use release version 1.3.0

deegree-ogcapi-features/src/main/resources/feature.html, deegree-ogcapi-features/src/main/resources/features.html
Prior to this PR the table of the features html view was empty if at least one feature contains a non-string property. The map contains the geometries of the features.
Ths PR fixes the  features and feature html view.
=> Fixed text.slice for non string values

.github/workflows/build_docker.yml
This PR removes the trigger on pushes on main branch to prevent pushing immediatly after release build a push of a new docker image to the previous release tag.
Required merge order:
- To be merged after PR #135 
Replaces PR #119
=> Removed trigger for push on main branch for pushing docker image

deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/cql2/Cql2FilterVisitor.java, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/DeegreeQueryBuilder.java, deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/cql2/Cql2ParserTest.java
This PR enhances OGC API - Features - Part 3 by T_AFTER({propertyName},{temporalInstance}) with {temporalInstance} = {instantInstance} and {instantInstance} = {dateInstant} | {timestampInstant}
=> Support of FILTER parameters with T_AFTER

docker/1.3/Dockerfile
This PR changes the war file from packaged to exploded inside a container image. The exploded (unpackaged) war file allows easier overwriting of configuration files (e.g. log4j2.properties) when running a container.
=> Changed deployment format to exploded of deegree-ogcapi.war file in container image

.github/workflows/build_docker.yml, docker/1.3/Dockerfile
This PR upgrades the docker file and the github actions build to v1.3.5
=> Post release bumped docker to v1.3.5

pom.xml
This PR upgrades deegree to 3.5.13 including changes introduced with PR https://github.com/deegree/deegree3/pull/1819 and https://github.com/deegree/deegree3/pull/1816
Upgraded dependencies:
- deegree webservices 3.5.13
- xmlunit 2.10.2
- swagger 2.1.29
=> Upgraded dependencies deegree to 3.5.13 and maven plugins

deegree-ogcapi-documentation/src/main/asciidoc/usage.adoc, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/OafResource.java, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/cql2/Cql2FilterVisitor.java, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/openapi/OafOpenApiFilter.java, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/DeegreeQueryBuilder.java, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/configuration/FilterProperty.java, deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/configuration/FilterPropertyType.java, deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/cql2/Cql2ParserTest.java, deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/workspace/DeegreeQueryBuilderTest.java
This PR extends the automated retrieval of supported queryables to also cover basic complex mappings at the top level.
**ATTENTION**: It is based on PR #163, which needs to be merged first!
=> Support simple XSD types as queryable

.github/workflows/build_docker.yml, docker/1.3/Dockerfile
This PR upgrades github action and dockerfile to v1.3.9
=> Post release - bumped docker to v1.3.9
