- deegree-ogcapi-config-htmlview/pom.xml
- deegree-ogcapi-datasets/pom.xml
- deegree-ogcapi-documentation/src/main/asciidoc/installation.adoc
- deegree-ogcapi-features/pom.xml
- pom.xml
Fixes #4, adds maven profile for java 11 and related dependencies, plugins updated as well
> Added support for Java 11

- jenkinsfiles/build/Jenkinsfile
adds a new build step using jdk 11
> added build step for jdk 11

- jenkinsfiles/build/Jenkinsfile
removes parameter for branch name and additional checkout of main branch in a multibranch pipeline setup.
This PR replaces PR #18.
> fixes #17 build pipeline fails in multibranch setup on Jenkins

- deegree-ogcapi-config-htmlview/src/main/java/org/deegree/services/oaf/config/htmlview/HtmlViewConfigResource.java
- deegree-ogcapi-config-htmlview/src/main/java/org/deegree/services/oaf/config/htmlview/HtmlViewConfiguration.java
- deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/OafResource.java
- deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/OgcApiFeatures.java
- deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/domain/html/HtmlPageConfiguration.java
- deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/configuration/DatasetMetadata.java
- deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/configuration/OafDatasetConfiguration.java
This PR improves log messages when initializing OgcApiFeatures controller.
> Enhanced log messages

- jenkinsfiles/build/Jenkinsfile
This PR removed Jenkins pipeline stage "Build-jdk8" (JDK 1.8 not longer supported)
> Removed Jenkins pipeline stage "Build-jdk8" (JDK 1.8 not longer supported)

- pom.xml
> Upgrades log4j2 dependency to latest bugfix version

- pom.xml
Fixes links to wrong github project and outdated demo url in pom.xml
> Fixes links to wrong github project in Maven POM

- pom.xml
- https://projects.eclipse.org/projects/ee4j.jersey/releases/2.36
- https://github.com/eclipse-ee4j/jersey/releases/tag/2.36
- https://github.com/eclipse-ee4j/jersey/wiki/Road-Map
> Upgrade jersey to 2.36

- pom.xml
Upgrade maven build plugins maven-jaxb2-plugin, build-helper-maven-plugin, maven-dependency-plugin, maven-deploy-plugin, maven-install-plugin, and maven-jar-plugin
> Upgrade maven build plugins

- checkstyle.xml
- deegree-ogcapi-documentation/pom.xml
- deegree-ogcapi-features/pom.xml
- deegree-ogcapi-webapp/pom.xml
- pom.xml
- settings.xml
- src/site/site.xml
Updated maven site plugins with configuration, and removed all duplicate maven definitions. Generation of maven site and javadoc is fixed.
> Updated maven site plugins

- pom.xml
This PR upgrade jackson from 2.13.4 to 2.14.1.
> Upgrade jackson from 2.13.4 to 2.14.1

- deegree-ogcapi-documentation/pom.xml
- deegree-ogcapi-webapp/pom.xml
- pom.xml
This PR upgrades the used maven plugins to the latest version.
> Upgraded Maven plugins to latest version

- pom.xml
This PR upgrades the dependencies for swagger, httpcore, joda-time, jackson and test libraries.
> Upgrade dependencies to latest bugfix version 

- jenkinsfiles/build/Jenkinsfile
- settings.xml
Updated jenkinsfile to use same build steps as main repo for deegree webservices 3.5
> Updated jenkinsfile to use build steps with JDK 11 as default

- jenkinsfiles/build/Jenkinsfile
- pom.xml
Removed deploy step from pipeline, and added junit47 plugin for surefire
> Removed deploy step from pipeline

- deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/OafResource.java
- deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/resource/Appschema.java
- deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/DeegreeDataAccess.java
- deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/configuration/FeatureTypeMetadata.java
- deegree-ogcapi-features/src/main/java/org/deegree/services/oaf/workspace/configuration/OafDatasetConfiguration.java
- deegree-ogcapi-features/src/test/java/org/deegree/services/oaf/TestData.java
This PRs fixes requesting features from other feature stores if multiple feature stores are configured providing feature types with the same name.
> Fixes mixing of feature stores

- docker/1.3/Dockerfile
Fixes the repo url to WAR file
> Fixes the repository url for downloading WAR file from nexus

- .github/workflows/build_docker.yml
- docker/1.3/Dockerfile
PR updates gh action for publishing image to version 1.3.1
> Post release bumped docker to v1.3.1

- deegree-ogcapi-features/src/main/resources/collections.html
This PR enables sorting of the collections in alphabetically order by id.
> Improved collections order in HTML by sorting by id

- .github/workflows/build_docker.yml
- docker/1.3/Dockerfile
PR updates gh action for publishing image to version 1.3.2
> Post release bumped docker to v1.3.2

- README.md
- deegree-ogcapi-documentation/pom.xml
- deegree-ogcapi-webapp/pom.xml
- pom.xml
This PR ugraded dependencies:
- swagger
- jackson
- antlr
and maven plugins to latest versions.
> Upgraded dependencies and maven plugins

- jenkinsfiles/build/Jenkinsfile
This PR applies the following changes to the pipeline:  
- using ssh key for authentication to connect to github, 
- using maven settings file from jenkins ci files, 
- using credentials stored in jenkins ci credentials for authentication to connect to nexus
> Fixed release pipeline to use managed credentials from jenkins ci

- .github/workflows/build_docker.yml
- docker/1.3/Dockerfile
This PR upgrades the docker file and build via github actions to v1.3.3
> Post release bumped docker to v1.3.3

- jenkinsfiles/build/Jenkinsfile
Split the pipeline steps for stage "RELEASE" into `release:prepare` and `release:perform`.
> Split pipeline step for release prepare and release perform

- .github/workflows/build_docker.yml
- docker/1.3/Dockerfile
- pom.xml
This PR upgrades the docker file and build via github actions to v1.3.4
> Post release bumped docker to v1.3.4

- deegree-ogcapi-documentation/src/main/asciidoc/configuration.adoc
- deegree-ogcapi-documentation/src/main/asciidoc/index.adoc
- deegree-ogcapi-documentation/src/main/asciidoc/installation.adoc
- deegree-ogcapi-documentation/src/main/asciidoc/intro.adoc
This PR contains minor improvements to the documentation clarifying the scope of the implementation with regards to the OGC API standards family.
> Minor improvements to the documentation

- deegree-ogcapi-documentation/pom.xml
- deegree-ogcapi-webapp/pom.xml
- pom.xml
This PR upgrades deegree to 3.5.12 including changes introduced with PR https://github.com/deegree/deegree3/pull/1806
> Upgraded dependencies deegree to 3.5.12, swagger to 2.2.30 and maven plugins

- .github/workflows/build_docker.yml
- docker/1.3/Dockerfile
This PR upgrades github action and dockerfile to v1.3.7
> Post release - bumped dockerfile to v1.3.7
